### ISSUE TITLE
toggle script

### ISSUE THREAD

**Issue by Idrinth** [Warric/New-Inline-Tier-Charts#10]
> Fiel 
> button to hide entire script into a single button that can resume when want because when you use it on multi-task on single screen your screen will be half and this script can get in your way when you try to access your potion belt / world chat.

**Comment by Idrinth** [comment]
I'm wondering, @Warric if moving it to mostly outside the scren when not hovering over the area might be a better idea

**Comment by Warric** [comment]
This might be a nice feature to have indeed :)
