### ISSUE TITLE
Add include domain

### ISSUE THREAD

**Issue by Idrinth** [Warric/New-Inline-Tier-Charts#2]
> // @include        http://web1.dawnofthedragons.com/live_standalone*

Also from the forums, will have a look what's actually hosted there, I always thought the standalone was at dawnofthedragons.com or dawnofthedragons.com/game

**Comment by Warric** [comment]
this was changed though in last update, to include
// @include http://web1.dawnofthedragons.com/live_standalone*

**Comment by Idrinth** [comment]
oh, then I guess we can already close this :)
